In [37]:
import os
os.chdir("D:\\Course code")


In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split



In [39]:
df = pd.read_excel('cancer patient data sets.xlsx')
df.head()

Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0         P1   33       1              2            4             5   
1        P10   17       1              3            1             5   
2       P100   35       1              4            5             6   
3      P1000   37       1              7            7             7   
4       P101   46       1              6            8             7   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                     4             3                     2              2   
1                     3             4                     2              2   
2                     5             5                     4              6   
3                     7             6                     7              7   
4                     7             7                     6              7   

   ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0  ...        3            4                    2         2   
1  ...        1            3                    7         8   
2  ...        8            7                    9         2   
3  ...        4            2                    3         1   
4  ...        3            2                    4         1   

   Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  Dry Cough  \
0                      3                         1              2          3   
1                      6                         2              1          7   
2                      1                         4              6          7   
3                      4                         5              6          7   
4                      4                         2              4          2   

   Snoring   Level  
0        4     Low  
1        2  Medium  
2        2    High  
3        5    High  
4        3    High  

[5 rows x 25 columns]

In [40]:
df = df.drop(['Patient Id'] , axis = 1)

In [41]:
labels = df.pop('Level')
df.head(2)

Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0   33       1              2            4             5   
1   17       1              3            1             5   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                     4             3                     2              2   
1                     3             4                     2              2   

   Obesity  ...  Coughing of Blood  Fatigue  Weight Loss  Shortness of Breath  \
0        4  ...                  4        3            4                    2   
1        2  ...                  3        1            3                    7   

   Wheezing  Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  \
0         2                      3                         1              2   
1         8                      6                         2              1   

   Dry Cough  Snoring  
0          3        4  
1          7        2  

[2 rows x 23 columns]

In [45]:
df = np.array(df , dtype='int')
type(df)

numpy.ndarray

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [44]:
labels = le.fit_transform(labels)
print(type(labels))


<class 'numpy.ndarray'>


In [46]:
x_train , x_test , y_train , y_test = train_test_split(df , labels , test_size = 0.2)

In [52]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier()

In [53]:
clf.fit(x_train , y_train)

SGDClassifier()

In [54]:
predictions = clf.predict(x_test)

In [56]:
result = clf.score(x_test,y_test)
print(result)

0.98


In [60]:
for i in range(len(x_test)):
    print(predictions[i] , y_test[i])

0 0
2 2
1 1
0 0
2 2
0 0
1 1
0 0
1 1
2 2
1 1
0 0
1 1
2 2
0 0
0 0
2 2
2 2
0 0
2 2
1 1
2 2
1 1
0 0
2 2
2 2
0 0
2 2
0 0
0 0
1 1
2 2
2 2
2 2
1 1
1 1
1 1
1 1
1 1
2 2
2 2
2 2
2 2
2 2
0 0
2 2
1 1
0 0
1 1
1 1
1 1
2 2
0 0
1 1
0 0
0 0
1 2
2 2
2 2
0 0
0 0
1 1
1 1
2 2
2 2
1 1
2 2
0 0
2 2
0 0
1 1
0 0
0 0
0 0
2 2
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
2 2
0 0
1 1
2 2
1 1
2 2
1 1
1 1
1 1
1 1
1 1
2 2
1 1
0 0
0 0
0 0
0 0
1 1
1 1
1 1
1 1
2 2
2 2
2 2
1 1
1 1
2 2
2 2
2 2
0 0
2 2
0 0
0 0
0 0
0 0
0 0
2 2
0 0
0 0
0 0
0 0
1 1
2 2
2 2
2 2
0 0
1 1
2 2
2 2
2 2
0 0
0 0
1 1
2 2
0 0
2 2
1 1
0 0
0 0
1 1
2 2
2 2
0 0
1 1
1 1
0 0
0 0
1 1
1 2
1 1
1 1
1 1
2 2
0 0
0 0
1 1
1 1
1 1
0 0
2 2
1 1
0 0
0 0
1 1
0 0
1 1
2 2
0 0
2 2
0 0
1 2
0 2
0 0
0 0
2 2
1 1
1 1
1 1
0 0
0 0
0 0
2 2
0 0
0 0
0 0
0 0
0 0
2 2
0 0
2 2
0 0
1 1
0 0
1 1
2 2
0 0


In [62]:
from sklearn.metrics import confusion_matrix
confusion_op = confusion_matrix(y_test , predictions)
print(confusion_op)

[[79  0  0]
 [ 0 58  0]
 [ 1  3 59]]


In [64]:
print(x_train )
print(x_test)

[[33  1  2 ...  2  3  4]
 [48  2  1 ...  1  2  1]
 [32  1  2 ...  2  5  1]
 ...
 [27  1  3 ...  3  4  3]
 [73  1  5 ...  1  6  2]
 [22  1  2 ...  2  1  1]]
[[48  1  6 ...  4  5  3]
 [36  2  2 ...  3  2  3]
 [48  1  4 ...  1  2  3]
 ...
 [28  1  6 ...  1  2  1]
 [38  2  6 ...  3  4  2]
 [49  1  6 ...  6  7  2]]
